name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: .github/images/update-readme-image@main
        with:
          IMG_ALT: <alt-message> #image alt to be displayed if image is not mapped correctly
